# Generated by Django 3.0.5 on 2020-04-19 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('timeToBeUsedFrom', models.TimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('bookingTime', models.TimeField(null=True)),
                ('bookingStatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(choices=[('Olympus', 'Olympus'), ('Valkyrie', 'Valkyrie'), ('Keza', 'Keza'), ('Kushinga', 'Kushinga'), ('Office', 'Office'), ('Athena', 'Athena'), ('Titans', 'Titans'), ('Gaga', 'Gaga'), ('Malaika', 'Malaika'), ('Jeshi', 'Jeshi'), ('Twawana', 'Twawana'), ('Classified', 'Classified')], max_length=50)),
                ('year_group', models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
